version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Database
      - DATABASE_URL=file:/app/data/prod.db
      
      # NextAuth.js - Set these in your environment
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-change-me-in-production}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      
      # Google OAuth - Set these in your environment
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # Google Maps API - Set these in your environment
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      
      # Cloudflare Tunnel / Proxy support - Set to true when behind proxy
      - TRUST_HOST=${TRUST_HOST:-false}
      
      # Production optimizations
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    
    volumes:
      # Persist database data
      - ./data:/app/data
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local